### ISSUE TITLE
Hi, brother, I have a question.

### ISSUE THREAD

**Issue by malajisi2** [danielbarion/L2JBlueHeart#2]
![111243](https://user-images.githubusercontent.com/44082779/46907507-1ca47380-cf46-11e8-8eeb-f64e3766c9b6.png)
Where can I modify or delete these tips when logging in to the game?

**Comment by danielbarion** [comment]
Hi,

`RGuard.ini`

```
# See the client shared online?
ShowOnlineInClient = True
```

**Comment by malajisi2** [comment]
no
