### ISSUE TITLE
Coluna faltante no backup

### ISSUE THREAD

**Issue by AnibalDuarte** [danielbarion/L2JBlueHeart#3]
A coluna _visual_item_id_ da tabela **items** não está presente no databaseSQL .

**Comment by danielbarion** [comment]
https://github.com/danielbarion/L2JBlueHeart/blob/master/databaseSQL/dressmeSQL/items.sql

**Comment by AnibalDuarte** [comment]
Eu adicionei ela, mas é bom colocar ela no SQL de instalação principal.
