### ISSUE TITLE
Pedido: mudança em sistema de Logs

### ISSUE THREAD

**Issue by AnibalDuarte** [danielbarion/L2JBlueHeart#6]
Hoje os logs são feitos em arquivos de texto, coisa tremendamente imprática porque esses logs ficam gigantescos em servidores com grande movimento e não são "cortados". Em um test server que fiz o item.log já tem 1GB de tamanho, coisa que poucos editores de texto conseguem dar e torna um pesadelo fazer qualquer busca.

Existe alguma config escondida que permita que esses logs sejam salvos no banco de dados? Se não, poderiam implementar?

**Comment by danielbarion** [comment]
Você tem razão @AnibalDuarte, esse é um ponto bem válido que precisa ser melhorado, talvez a forma mais rápida de resolver isso (talvez a melhor também), seja adicionar a data no arquivo de log, como ?

o logger criaria uma pasta caso não existisse (com o mês e o ano), e dentro dela iria criar os logs com as datas (dia mes e ano), assim antes de escrever ele iria checar o dia atual, tentar encontrar e caso não encontrasse, criaria um novo (assim limitaria os logs por dia, que dariam arquivos menores);
Hoje ele só faz isso na inicialização do gameserver (criar arquivos novos de logs), mas pra um servidor que fica 24h online, a forma como está hoje resulta no que você relatou.

Essa é a forma mais rápida e simples de resolver (acredito que não é a unica forma);

Eu e o turtle estamos sem tempo para codar, estamos só tirando dúvidas da galera sobre o projeto e estou cuidando dos repositórios (trabalho durante o dia e faço faculdade a noite, final de semana tenho compromissos);

Você manja fazer essa implementação por favor ?

**Comment by AnibalDuarte** [comment]
Eu parei pra olhar e fiz algo que está funcional... não está 100% mas já é muito melhor do que o sistema de arquivo atual.

https://github.com/danielbarion/JBlueHeart-Source/pull/16

PS.: ele é só para o item_log.

**Comment by danielbarion** [comment]
Obrigado campeão,
Ficou excelente!
